"""add file_path to documents

Revision ID: 1b9b797050ee
Revises: 211c0f5f9a56
Create Date: 2026-07-13 16:30:30.919394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b9b797050ee'
down_revision: Union[str, Sequence[str], None] = '211c0f5f9a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_path', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_path')
    # ### end Alembic commands ###
