import { useEffect, useRef, useState, useCallback } from 'react';
import Card from '../components/ui/Card';
import Badge from '../components/ui/Badge';
import Button from '../components/ui/Button';
import { Input } from '../components/ui/Field';
import MicButton from '../components/voice/MicButton';
import Waveform from '../components/voice/Waveform';
import TranscriptPanel from '../components/voice/TranscriptPanel';
import Timeline from '../components/voice/Timeline';
import { IconPause, IconPlay, IconRestart, IconStop, IconSend } from '../components/ui/icons';
import './conversation.css';

const SAMPLE_USER_LINES = [
  'Hi, I want to check my account balance.',
  'Can you tell me my last three transactions?',
  'How do I set up autopay for my credit card?',
  'I need to report a lost debit card.',
];

const SAMPLE_AI_REPLIES = {
  'Hi, I want to check my account balance.': 'Sure — your Northfield Checking account balance is ₹84,210.50 as of this morning. Would you like a breakdown of recent activity?',
  'Can you tell me my last three transactions?': 'Your last three transactions were: ₹1,200 at Cafe Nolan on July 3rd, ₹4,500 rent payment on July 1st, and a ₹320 refund from Blinkit on June 29th.',
  'How do I set up autopay for my credit card?': 'You can enable autopay from Settings → Payments. I can also set the minimum-due autopay for you right now — want me to go ahead?',
  'I need to report a lost debit card.': 'I\u2019m sorry to hear that. I\u2019ve temporarily frozen your debit card ending in 4471 and started a replacement request — it should arrive in 5 to 7 business days.',
};

function nowTs() {
  return new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' });
}

export default function VoiceConversation() {
  const [status, setStatus] = useState('idle'); // idle | listening | thinking | speaking | paused
  const [messages, setMessages] = useState([]);
  const [liveCaption, setLiveCaption] = useState('');
  const [timelineEvents, setTimelineEvents] = useState([
    { type: 'system', label: 'Session connected to Banking Assistant', ts: nowTs() },
  ]);
  const [typedInput, setTypedInput] = useState('');
  const [playback, setPlayback] = useState({ playing: false, progress: 0, duration: 6 });
  const [lastAiMessage, setLastAiMessage] = useState(null);
  const [analyserNode, setAnalyserNode] = useState(null);

  const analyserRef = useRef(null);
  const streamRef = useRef(null);
  const audioCtxRef = useRef(null);
  const timeoutsRef = useRef([]);
  const playbackTimerRef = useRef(null);
  const lineIndexRef = useRef(0);

  const pushTimeline = useCallback((label, type = 'system') => {
    setTimelineEvents((evs) => [...evs, { label, type, ts: nowTs() }]);
  }, []);

  const clearTimers = () => {
    timeoutsRef.current.forEach(clearTimeout);
    timeoutsRef.current = [];
  };

  useEffect(() => () => {
    clearTimers();
    clearInterval(playbackTimerRef.current);
    streamRef.current?.getTracks().forEach((t) => t.stop());
    audioCtxRef.current?.close?.();
  }, []);

  const respondTo = useCallback((userText) => {
    setStatus('thinking');
    pushTimeline('Transcript sent to LLM Orchestrator', 'system');
    const t1 = setTimeout(() => {
      const reply = SAMPLE_AI_REPLIES[userText] || 'Got it — let me pull that up for you. Is there anything else I can check while I do that?';
      setMessages((m) => [...m, { speaker: 'ai', text: reply, ts: nowTs() }]);
      setLastAiMessage(reply);
      pushTimeline('Response generated by LLM', 'system');
      setStatus('speaking');
      pushTimeline('Audio playback started (TTS)', 'system');
      startPlayback(reply);
      const t2 = setTimeout(() => {
        setStatus('idle');
      }, 1600);
      timeoutsRef.current.push(t2);
    }, 1100);
    timeoutsRef.current.push(t1);
  }, [pushTimeline]);

  const startPlayback = (text) => {
    clearInterval(playbackTimerRef.current);
    const duration = Math.max(4, Math.min(14, Math.round(text.length / 16)));
    setPlayback({ playing: true, progress: 0, duration });
    const startedAt = Date.now();
    playbackTimerRef.current = setInterval(() => {
      const elapsed = (Date.now() - startedAt) / 1000;
      if (elapsed >= duration) {
        setPlayback((p) => ({ ...p, playing: false, progress: duration }));
        clearInterval(playbackTimerRef.current);
      } else {
        setPlayback((p) => ({ ...p, progress: elapsed }));
      }
    }, 120);
  };

  const togglePlayback = () => {
    setPlayback((p) => {
      if (!p.playing && p.progress >= p.duration) {
        startPlayback(lastAiMessage || '');
        return p;
      }
      const next = { ...p, playing: !p.playing };
      if (next.playing) {
        const startedAt = Date.now() - p.progress * 1000;
        clearInterval(playbackTimerRef.current);
        playbackTimerRef.current = setInterval(() => {
          const elapsed = (Date.now() - startedAt) / 1000;
          if (elapsed >= p.duration) {
            setPlayback((pp) => ({ ...pp, playing: false, progress: p.duration }));
            clearInterval(playbackTimerRef.current);
          } else {
            setPlayback((pp) => ({ ...pp, progress: elapsed }));
          }
        }, 120);
      } else {
        clearInterval(playbackTimerRef.current);
      }
      return next;
    });
  };

  const restartPlayback = () => {
    if (lastAiMessage) startPlayback(lastAiMessage);
  };

  const simulateListening = useCallback(async () => {
    setStatus('listening');
    pushTimeline('Recording started', 'system');

    // Try real mic capture for an authentic waveform; fall back silently.
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      streamRef.current = stream;
      const ctx = new (window.AudioContext || window.webkitAudioContext)();
      audioCtxRef.current = ctx;
      const source = ctx.createMediaStreamSource(stream);
      const analyser = ctx.createAnalyser();
      analyser.fftSize = 256;
      source.connect(analyser);
      analyserRef.current = analyser;
      setAnalyserNode(analyser);
    } catch {
      analyserRef.current = null;
      setAnalyserNode(null);
    }

    const line = SAMPLE_USER_LINES[lineIndexRef.current % SAMPLE_USER_LINES.length];
    lineIndexRef.current += 1;
    const words = line.split(' ');
    let built = '';
    words.forEach((w, i) => {
      const t = setTimeout(() => {
        built = built ? `${built} ${w}` : w;
        setLiveCaption(built);
        if (i === words.length - 1) {
          const t2 = setTimeout(() => {
            setLiveCaption('');
            setMessages((m) => [...m, { speaker: 'user', text: line, ts: nowTs() }]);
            pushTimeline('Speech transcribed', 'system');
            stopMic();
            respondTo(line);
          }, 350);
          timeoutsRef.current.push(t2);
        }
      }, i * 260);
      timeoutsRef.current.push(t);
    });
  }, [pushTimeline, respondTo]);

  const stopMic = () => {
    streamRef.current?.getTracks().forEach((t) => t.stop());
    audioCtxRef.current?.close?.();
    streamRef.current = null;
    audioCtxRef.current = null;
    analyserRef.current = null;
    setAnalyserNode(null);
  };

  const handleMicClick = () => {
    if (status === 'listening') {
      clearTimers();
      stopMic();
      setLiveCaption('');
      setStatus('idle');
      pushTimeline('Recording stopped by user', 'system');
      return;
    }
    if (status === 'idle') {
      simulateListening();
    }
  };

  const handlePause = () => {
    if (status === 'listening' || status === 'speaking') {
      setStatus('paused');
      clearInterval(playbackTimerRef.current);
      pushTimeline('Conversation paused', 'alert');
    } else if (status === 'paused') {
      setStatus('idle');
      pushTimeline('Conversation resumed', 'system');
    }
  };

  const handleStop = () => {
    clearTimers();
    clearInterval(playbackTimerRef.current);
    stopMic();
    setLiveCaption('');
    setStatus('idle');
    setPlayback((p) => ({ ...p, playing: false }));
    pushTimeline('Session stopped', 'alert');
  };

  const handleRestart = () => {
    clearTimers();
    clearInterval(playbackTimerRef.current);
    stopMic();
    setMessages([]);
    setLiveCaption('');
    setLastAiMessage(null);
    setPlayback({ playing: false, progress: 0, duration: 6 });
    setStatus('idle');
    lineIndexRef.current = 0;
    setTimelineEvents([{ type: 'system', label: 'Session restarted', ts: nowTs() }]);
  };

  const handleTypeSubmit = (e) => {
    e.preventDefault();
    const text = typedInput.trim();
    if (!text) return;
    setMessages((m) => [...m, { speaker: 'user', text, ts: nowTs() }]);
    pushTimeline('Message sent via text input', 'system');
    setTypedInput('');
    respondTo(text);
  };

  const statusLabel = {
    idle: 'Tap the microphone to start speaking',
    listening: 'Listening…',
    thinking: 'Thinking…',
    speaking: 'Speaking response…',
    paused: 'Conversation paused',
  }[status];

  const progressPct = playback.duration ? Math.min(100, (playback.progress / playback.duration) * 100) : 0;

  return (
    <div className="container-page">
      <div className="conv-header">
        <div className="conv-persona">
          <span className="conv-persona-avatar">BA</span>
          <div>
            <div className="conv-persona-name">Banking Assistant</div>
            <div className="conv-persona-sub">Northfield Bank · English (US) · Voice: Aria</div>
          </div>
        </div>
        <div className="conn-status">
          <span className="conn-dot" />
          Connected · 118ms
        </div>
      </div>

      <div className="conv-grid">
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <Card padded={false}>
            <div className="conv-stage">
              <div className="conv-stage-waveform">
                <Waveform
                  analyser={analyserNode}
                  active={status === 'listening' || status === 'speaking'}
                  speaking={status === 'speaking'}
                />
              </div>
              <MicButton status={status === 'paused' ? 'idle' : status} onClick={handleMicClick} />
              <div className="conv-stage-status">{statusLabel}</div>

              <div className="conv-controls">
                <button className="conv-control-btn" onClick={handlePause} disabled={status === 'idle'} title={status === 'paused' ? 'Resume' : 'Pause'} aria-label="Pause or resume">
                  {status === 'paused' ? <IconPlay width={17} height={17} /> : <IconPause width={17} height={17} />}
                </button>
                <button className="conv-control-btn" onClick={handleStop} disabled={status === 'idle'} title="Stop" aria-label="Stop">
                  <IconStop width={16} height={16} />
                </button>
                <button className="conv-control-btn" onClick={handleRestart} title="Restart conversation" aria-label="Restart">
                  <IconRestart width={17} height={17} />
                </button>
              </div>

              <form className="conv-type-row" onSubmit={handleTypeSubmit}>
                <Input
                  placeholder="Or type a message instead…"
                  value={typedInput}
                  onChange={(e) => setTypedInput(e.target.value)}
                />
                <Button type="submit" variant="secondary" icon={<IconSend width={15} height={15} />}>Send</Button>
              </form>
            </div>
          </Card>

          <Card title="Conversation timeline" subtitle="System events for this session">
            <Timeline events={timelineEvents} />
          </Card>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <Card title="Live transcript" subtitle="What's been said so far" className="conv-transcript-card">
            <TranscriptPanel messages={messages} liveCaption={liveCaption} />
          </Card>

          <Card title="AI response" subtitle="Latest generated reply">
            {lastAiMessage ? (
              <>
                <p className="ai-response-text">{lastAiMessage}</p>
                <div className="player-row">
                  <button className="conv-control-btn" onClick={togglePlayback} aria-label={playback.playing ? 'Pause playback' : 'Play response'}>
                    {playback.playing ? <IconPause width={15} height={15} /> : <IconPlay width={15} height={15} />}
                  </button>
                  <div className="player-progress" onClick={(e) => {
                    const rect = e.currentTarget.getBoundingClientRect();
                    const pct = (e.clientX - rect.left) / rect.width;
                    setPlayback((p) => ({ ...p, progress: pct * p.duration }));
                  }}>
                    <div className="player-progress-fill" style={{ width: `${progressPct}%` }} />
                  </div>
                  <span className="player-time">{playback.progress.toFixed(0)}s / {playback.duration}s</span>
                  <button className="conv-control-btn" onClick={restartPlayback} aria-label="Restart playback">
                    <IconRestart width={14} height={14} />
                  </button>
                </div>
              </>
            ) : (
              <p className="ai-response-empty">The assistant&apos;s next spoken reply will appear here with playback controls.</p>
            )}
          </Card>
        </div>
      </div>
    </div>
  );
}
